### PR TITLE
user middleware created, and backend can record the login time now

### PR DESCRIPTION
**Pull request by WeiyuSun**
create middleware for User

### CODE REVIEW

**Comment by ShahzaibParacha** [comment]
everything looks good

**Comment by ShahzaibParacha** [comment]
Can you also implement the linter? There are some files that do no have a new line and linter can fix that

**Review by ShahzaibParacha — APPROVED** [review]
@WeiyuSun looks good to me

**Comment by WeiyuSun** [comment]
> Can you also implement the linter? There are some files that do no have a new line and linter can fix that

yes, do it later

**Pull request merged**
