### PR TITLE
Sp/feature/home feed and navbar

### PR DESCRIPTION
**Pull request by ShahzaibParacha**

### CODE REVIEW

**Review by orangeboy55555 — DISMISSED** [review]
Sounds good!

**Review by DaTanUmanitoba — APPROVED** [review]
It seems all good.

**Review by DaTanUmanitoba — DISMISSED** [review]
good!

**Review by orangeboy55555 — APPROVED** [review]
Looks good!

**Review by WeiyuSun — APPROVED** [review]
good job

**Pull request merged**
